// Mock Data for Forique Jewelry E-commerce

export const categories = [
    { id: "earrings", name: "Earrings", slug: "earrings", image: "/products/kundan-jhumka.png", icon: "💎", count: 156 },
    { id: "necklaces", name: "Necklaces", slug: "necklaces", image: "/products/celestial-necklace.png", icon: "📿", count: 89 },
    { id: "bracelets", name: "Bracelets", slug: "bracelets", image: "/products/rose-gold-bracelet.png", icon: "⌚", count: 124 },
    { id: "rings", name: "Rings", slug: "rings", image: "/products/infinity-ring.png", icon: "💍", count: 98 },
    { id: "bangles", name: "Bangles", slug: "bangles", image: "/products/temple-bangles.png", icon: "⭕", count: 67 },
    { id: "anklets", name: "Anklets", slug: "anklets", image: "/products/rose-gold-bracelet.png", icon: "✨", count: 45 },
    { id: "maang-tikka", name: "Maang Tikka", slug: "maang-tikka", image: "/products/kundan-jhumka.png", icon: "👑", count: 34 },
    { id: "nose-pins", name: "Nose Pins", slug: "nose-pins", image: "/products/pearl-ring.png", icon: "💫", count: 56 },
];

export const brands = [
    { id: "velora", name: "Velora", logo: "/brands/velora.png", tagline: "Timeless Elegance" },
    { id: "aureum", name: "Aureum", logo: "/brands/aureum.png", tagline: "Golden Dreams" },
    { id: "crystelle", name: "Crystelle", logo: "/brands/crystelle.png", tagline: "Crystal Clear Beauty" },
    { id: "silverine", name: "Silverine", logo: "/brands/crystelle.png", tagline: "Silver Sophistication" },
    { id: "ethnic-treasures", name: "Ethnic Treasures", logo: "/brands/ethnic-treasures.png", tagline: "Heritage Reimagined" },
    { id: "luxe-craft", name: "Luxe Craft", logo: "/brands/luxe-craft.png", tagline: "Crafted with Love" },
];

export const products = [
    {
        id: "prod-1",
        name: "Royal Kundan Jhumka Earrings",
        slug: "royal-kundan-jhumka-earrings",
        brand: { id: "ethnic-treasures", name: "Ethnic Treasures", logo: "/brands/ethnic-treasures.png" },
        category: { id: "earrings", name: "Earrings", slug: "earrings" },
        price: 2499,
        originalPrice: 3499,
        discount: 29,
        images: ["/products/kundan-jhumka.png", "/categories/earrings.png"],
        colors: ["Antique Gold", "Gold"],
        materials: ["Copper", "Kundan", "Pearl"],
        description: "Exquisite royal kundan jhumka earrings featuring intricate polki diamonds, pearls, and delicate meenakari enamel work. Perfect for weddings and festive occasions.",
        features: ["Handcrafted", "Real Meenakari", "Pearl Drops"],
        rating: 4.9,
        reviewCount: 567,
        inStock: true,
        isNew: true,
        isBestseller: true,
        tags: ["bridal", "wedding", "festive", "kundan"],
    },
    {
        id: "prod-2",
        name: "Celestial Layered Necklace",
        slug: "celestial-layered-necklace",
        brand: { id: "velora", name: "Velora", logo: "/brands/velora.png" },
        category: { id: "necklaces", name: "Necklaces", slug: "necklaces" },
        price: 1899,
        originalPrice: 2499,
        discount: 24,
        images: ["/products/celestial-necklace.png"],
        colors: ["Gold"],
        materials: ["Gold Plated", "Brass"],
        description: "Modern celestial-inspired layered necklace with moon, star, and gemstone charms. Perfect for everyday elegance.",
        features: ["Triple Layer", "Adjustable Length", "Nickel Free"],
        rating: 4.8,
        reviewCount: 234,
        inStock: true,
        isNew: true,
        isBestseller: true,
        tags: ["layered", "celestial", "everyday", "modern"],
    },
    {
        id: "prod-3",
        name: "Rose Gold Diamond Bracelet",
        slug: "rose-gold-diamond-bracelet",
        brand: { id: "crystelle", name: "Crystelle", logo: "/brands/crystelle.png" },
        category: { id: "bracelets", name: "Bracelets", slug: "bracelets" },
        price: 1299,
        originalPrice: 1799,
        discount: 28,
        images: ["/products/rose-gold-bracelet.png"],
        colors: ["Rose Gold", "Gold", "Silver"],
        materials: ["Rose Gold Plated", "CZ Diamonds"],
        description: "Delicate rose gold bracelet with sparkling CZ diamond accents. Minimalist design perfect for layering.",
        features: ["Adjustable", "CZ Stones", "Tarnish Resistant"],
        rating: 4.7,
        reviewCount: 189,
        inStock: true,
        isNew: true,
        isBestseller: false,
        tags: ["minimalist", "rose gold", "daily wear", "elegant"],
    },
    {
        id: "prod-4",
        name: "Temple Gold Bangles Set",
        slug: "temple-gold-bangles-set",
        brand: { id: "ethnic-treasures", name: "Ethnic Treasures", logo: "/brands/ethnic-treasures.png" },
        category: { id: "bangles", name: "Bangles", slug: "bangles" },
        price: 2799,
        originalPrice: 3999,
        discount: 30,
        images: ["/products/temple-bangles.png"],
        colors: ["Antique Gold"],
        materials: ["Copper", "Gold Plated"],
        description: "Traditional temple jewelry inspired bangles set. Features intricate kundan work with emerald accents.",
        features: ["Set of 6", "Temple Design", "1.5 Micron Gold Plating"],
        rating: 4.9,
        reviewCount: 312,
        inStock: true,
        isNew: false,
        isBestseller: true,
        tags: ["traditional", "temple", "festive", "set"],
    },
    {
        id: "prod-5",
        name: "Vintage Pearl Statement Ring",
        slug: "vintage-pearl-statement-ring",
        brand: { id: "luxe-craft", name: "Luxe Craft", logo: "/brands/luxe-craft.png" },
        category: { id: "rings", name: "Rings", slug: "rings" },
        price: 1599,
        originalPrice: 2199,
        discount: 27,
        images: ["/products/pearl-ring.png"],
        colors: ["Gold", "Silver"],
        materials: ["Brass", "Freshwater Pearl"],
        description: "A stunning vintage-inspired statement ring featuring a genuine freshwater pearl set in an ornate design.",
        features: ["Real Freshwater Pearl", "Adjustable Size", "Antique Finish"],
        rating: 4.6,
        reviewCount: 156,
        inStock: true,
        isNew: false,
        isBestseller: true,
        tags: ["statement", "vintage", "party", "pearl"],
    },
    {
        id: "prod-6",
        name: "Crystal Cascade Jhumkas",
        slug: "crystal-cascade-jhumkas",
        brand: { id: "crystelle", name: "Crystelle", logo: "/brands/crystelle.png" },
        category: { id: "earrings", name: "Earrings", slug: "earrings" },
        price: 1899,
        originalPrice: 2499,
        discount: 24,
        images: ["/products/crystal-jhumkas.png", "/categories/earrings.png"],
        colors: ["Gold", "Oxidized Silver"],
        materials: ["Brass", "Crystal", "Gold Plated"],
        description: "Beautiful cascading jhumkas adorned with sparkling crystals. These statement earrings add glamour to any outfit.",
        features: ["Premium Crystals", "Lightweight", "Secure Closure"],
        rating: 4.8,
        reviewCount: 423,
        inStock: true,
        isNew: false,
        isBestseller: true,
        tags: ["bridal", "festive", "statement", "crystal"],
    },
    {
        id: "prod-7",
        name: "Emerald Teardrop Pendant",
        slug: "emerald-teardrop-pendant",
        brand: { id: "aureum", name: "Aureum", logo: "/brands/aureum.png" },
        category: { id: "necklaces", name: "Necklaces", slug: "necklaces" },
        price: 1999,
        originalPrice: 2799,
        discount: 29,
        images: ["/products/emerald-pendant.png"],
        colors: ["Gold"],
        materials: ["Brass", "Synthetic Emerald", "Gold Plated"],
        description: "An elegant teardrop pendant featuring a stunning synthetic emerald stone surrounded by delicate crystals.",
        features: ["Synthetic Emerald", "18 Inch Chain", "Lobster Clasp"],
        rating: 4.8,
        reviewCount: 178,
        inStock: true,
        isNew: false,
        isBestseller: true,
        tags: ["elegant", "party", "gift", "emerald"],
    },
    {
        id: "prod-8",
        name: "Infinity Love Ring",
        slug: "infinity-love-ring",
        brand: { id: "luxe-craft", name: "Luxe Craft", logo: "/brands/luxe-craft.png" },
        category: { id: "rings", name: "Rings", slug: "rings" },
        price: 899,
        originalPrice: 1299,
        discount: 31,
        images: ["/products/infinity-ring.png"],
        colors: ["Rose Gold", "Silver", "Gold"],
        materials: ["Sterling Silver", "Rose Gold Plated"],
        description: "A romantic infinity symbol ring, perfect as a gift for your loved one.",
        features: ["Sterling Silver Base", "Adjustable", "Gift Box Included"],
        rating: 4.6,
        reviewCount: 445,
        inStock: true,
        isNew: true,
        isBestseller: true,
        tags: ["romantic", "gift", "daily wear", "infinity"],
    },
];

export const banners = [
    {
        id: "1",
        title: "New Season Collection",
        subtitle: "Discover the elegance of our Spring 2026 arrivals",
        cta: "Shop Now",
        image: "/categories/necklaces.png",
        link: "/category/new-arrivals",
    },
    {
        id: "2",
        title: "Bridal Jewelry",
        subtitle: "Make your special day even more beautiful",
        cta: "Explore Collection",
        image: "/products/product-1.png",
        link: "/category/bridal",
    },
    {
        id: "3",
        title: "Up to 40% Off",
        subtitle: "Limited time offer on selected pieces",
        cta: "Shop Sale",
        image: "/categories/bangles.png",
        link: "/category/sale",
    },
];

export const offers = [
    {
        id: "1",
        title: "First Order Discount",
        description: "Get 15% off on your first purchase",
        code: "FIRST15",
        validUntil: "2026-02-28",
    },
    {
        id: "2",
        title: "Free Shipping",
        description: "Free delivery on orders above ₹999",
        code: null,
        validUntil: null,
    },
    {
        id: "3",
        title: "Buy 2 Get 1 Free",
        description: "On selected earrings collection",
        code: "B2G1",
        validUntil: "2026-01-31",
    },
];

export const mockUser = {
    id: "user-1",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+91 98765 43210",
    avatar: null,
    addresses: [
        {
            id: "addr-1",
            type: "Home",
            name: "Priya Sharma",
            phone: "+91 98765 43210",
            line1: "203, Rose Apartment",
            line2: "Bandra West",
            city: "Mumbai",
            state: "Maharashtra",
            pincode: "400050",
            isDefault: true,
        },
        {
            id: "addr-2",
            type: "Office",
            name: "Priya Sharma",
            phone: "+91 98765 43210",
            line1: "5th Floor, Tech Park",
            line2: "Andheri East",
            city: "Mumbai",
            state: "Maharashtra",
            pincode: "400069",
            isDefault: false,
        },
    ],
    stylePassport: {
        skinTone: "Warm",
        preferredMetal: "Gold",
        preferredStyle: ["Traditional", "Minimalist"],
        wristSize: "2.4",
        ringSize: "6",
    },
    refundWallet: 250,
};

export const mockOrders = [
    {
        id: "ORD-2026-001234",
        date: "2026-01-05",
        status: "Delivered",
        items: [
            { productId: "prod-1", name: "Royal Kundan Jhumka Earrings", image: "/products/product-1.png", quantity: 1, price: 2499 },
            { productId: "prod-3", name: "Rose Gold Diamond Bracelet", image: "/products/product-3.png", quantity: 1, price: 1299 },
        ],
        subtotal: 3798,
        shipping: 0,
        discount: 380,
        total: 3418,
        address: mockUser.addresses[0],
        paymentMethod: "UPI",
        trackingNumber: "DL1234567890",
        canReview: true,
    },
    {
        id: "ORD-2026-001156",
        date: "2025-12-28",
        status: "Shipped",
        items: [
            { productId: "prod-2", name: "Celestial Layered Necklace", image: "/products/product-2.png", quantity: 1, price: 1899 },
        ],
        subtotal: 1899,
        shipping: 0,
        discount: 190,
        total: 1709,
        address: mockUser.addresses[0],
        paymentMethod: "Credit Card",
        trackingNumber: "DL9876543210",
        canReview: false,
    },
];

export const reviews = [
    {
        id: "rev-1",
        productId: "prod-1",
        user: { name: "Anita M.", avatar: null },
        rating: 5,
        title: "Absolutely gorgeous!",
        comment: "These earrings are even more beautiful in person. The quality is amazing and they're surprisingly lightweight.",
        date: "2026-01-02",
        images: [],
        verified: true,
    },
    {
        id: "rev-2",
        productId: "prod-1",
        user: { name: "Sneha K.", avatar: null },
        rating: 4,
        title: "Beautiful but delicate",
        comment: "Love the design! Just be careful while handling as they're quite delicate. Perfect for special occasions.",
        date: "2025-12-28",
        images: [],
        verified: true,
    },
    {
        id: "rev-3",
        productId: "prod-2",
        user: { name: "Meera P.", avatar: null },
        rating: 5,
        title: "Perfect layer look!",
        comment: "The celestial charms are so pretty. I wear it every day!",
        date: "2025-12-15",
        images: [],
        verified: true,
    },
];

// Helper functions
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getProductsByCategory = (slug: string) => products.filter(p => p.category.slug === slug);
export const getBestsellers = () => products.filter(p => p.isBestseller);
export const getNewArrivals = () => products.filter(p => p.isNew);
export const searchProducts = (query: string) => {
    const lowerQuery = query.toLowerCase();
    return products.filter(
        p => p.name.toLowerCase().includes(lowerQuery) ||
            p.description.toLowerCase().includes(lowerQuery) ||
            p.tags.some(t => t.includes(lowerQuery))
    );
};
